version: "3.2"

services:
  gan1:
    build:
      context: .
      dockerfile: settings/gan1.Dockerfile
    container_name: ganmorph1
    tty: true
    volumes:
      - type: bind
        source: StyleGAN_LatentEditor
        target: /root/work
    ports:
      - "8081:8888"
    command: jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
