#!/bin/sh

# 推移中の潜在変数の取得．

python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/DI.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/FE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/HA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU09.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU10.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/AN.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/FE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/HA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU09.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU10.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/DI.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/HA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU09.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU10.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/FE.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU09.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU10.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/HA.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU10.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU09.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU12.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU10.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU12L.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU12LW.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12L.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU12R.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12LW.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU14.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU12R.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU15.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU14.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU16.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU15.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU17.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU16.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU18.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU17.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU20.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU18.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU22.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU20.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU23.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU22.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/LFAU24.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU23.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/LFAU25.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU24.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/LFAU26.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU25.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/LFAU28.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU26.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/LFAU34.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU28.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU34.npy --latent_file2 latent_W/NE.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU34.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU34.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU34.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/LFAU34.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/NE.npy --latent_file2 latent_W/SA.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/NE.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/NE.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/NE.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/SA.npy --latent_file2 latent_W/SU.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/SA.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/SA.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/SU.npy --latent_file2 latent_W/UFAU02.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/SU.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/
python make_morphed_latent.py --latent_file1 latent_W/UFAU02.npy --latent_file2 latent_W/UFAU04.npy --folder latent_W/